import os
import base64
from typing import List
from google import genai
from google.genai import types
from PIL import Image
import io
from config import settings

client = genai.Client(api_key=settings.gemini_api_key)
MODEL = "gemini-2.5-flash-image"


async def translate_image(image_path: str, target_language: str, language_name: str) -> Image.Image:
    """
    Translate marketing text in an image using Gemini's image generation.
    Sends the original image with a prompt to translate and returns the generated image.
    """

    # Read and encode the image
    with open(image_path, "rb") as f:
        image_bytes = f.read()

    # Detect format
    img = Image.open(io.BytesIO(image_bytes))
    width, height = img.size

    prompt = f"""Edit this product marketing image by translating ALL the surrounding marketing text to {language_name}.

IMPORTANT RULES:
1. TRANSLATE all marketing/promotional text that surrounds the product (slogans, descriptions, feature callouts, percentages, claims, headlines)
2. DO NOT translate or modify ANY text that is printed ON the product itself (brand names on bottles/packaging, ingredient lists, product labels)
3. Keep the EXACT same visual style, fonts, colors, and layout as the original
4. Maintain the same image quality and resolution ({width}x{height})
5. The translated text should fit naturally in the same spaces as the original
6. Preserve all product imagery, backgrounds, and design elements exactly

Return the edited image with the marketing text translated to {language_name}."""

    # Upload the image file
    uploaded_file = client.files.upload(file=image_path)

    response = client.models.generate_content(
        model=MODEL,
        contents=[uploaded_file, prompt],
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
        ),
    )

    # Extract the generated image from response
    result_image = None
    for part in response.candidates[0].content.parts:
        if part.inline_data is not None:
            image_data = part.inline_data.data
            result_image = Image.open(io.BytesIO(image_data))
            break

    # Cleanup uploaded file
    try:
        client.files.delete(name=uploaded_file.name)
    except Exception:
        pass

    if result_image is None:
        raise Exception("No image was generated by Gemini")

    # Resize to original dimensions if needed
    if result_image.size != (width, height):
        result_image = result_image.resize((width, height), Image.LANCZOS)

    return result_image
